version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ci-cd-react
    container_name: ci-cd-react-container
    restart: unless-stopped
    ports:
      - '49120:3000'
    volumes:
      - ./:/ci-cd-react